---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.10
- name: ubuntu-14.04
- name: ubuntu-12.04
- name: debian-7.2.0
- name: debian-6.0.8

suites:
- name: all
  run_list:
  - recipe[minitest-handler]
  - recipe[resolvconf]
  attributes:
    resolvconf:
      nameserver: [ '8.8.8.8', '8.8.4.4' ]
      domain: 'example.com'
      search: [ test.com, example.com ]
      sortlist: [ '130.155.160.0/255.255.240.0 130.155.0.0' ]
      options: rotate

- name: without-options
  run_list:
  - recipe[minitest-handler]
  - recipe[resolvconf]
  attributes:
    resolvconf:
      nameserver: '8.8.8.8'
      search: test.com

- name: only-nameserver
  run_list:
  - recipe[minitest-handler]
  - recipe[resolvconf]
  attributes:
    resolvconf:
      nameserver: '8.8.8.8'
